# Generated by Django 4.2 on 2023-05-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_alter_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='registration_number',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
