# Generated by Django 4.2 on 2023-05-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patient_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='location',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('NCR', 'NCR'), ('Outside Delhi', 'Outside Delhi')], max_length=13),
        ),
    ]
