# Generated by Django 4.2 on 2023-05-06 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_rename_registration_number_patient_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='registration_number',
        ),
    ]
