# Generated by Django 4.2 on 2023-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_rename_patient_id_patient_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
